import { Button, VerticalBox , LineEdit, ScrollView} from "std-widgets.slint";

export struct Article {
    date: string,
    title: string,
    content: string,
}

export global AppData {
    in-out property <[Article]> articles;
    in-out property <string> username: "";
}

export component App inherits Window {
    title: "N Launcher";
    preferred-width: 500px;
    preferred-height: 300px;

    VerticalBox {
        alignment: start;

        in-out property <length> title_height <=> title.height;

        title := Text {
            text: "Notizie";
            font-size: 24px;
            horizontal-alignment: center;
            height: 30px;
        }

        ScrollView {
            min-height: title_height + 20px;
            preferred-height: root.height * 0.8;

            for article in AppData.articles: articles_text := VerticalLayout {
                padding: 5px;
                alignment: start;
                HorizontalLayout {
                    alignment: start;
                    Text {
                        text: article.title;
                        font-size: 20px;
                    }
                    Rectangle {
                        width: 5px;
                    }
                    Text {
                        vertical-alignment: center;
                        text: article.date;
                        font-size: 10px;
                        color: grey;
                    }
                }
                Text {
                    text: article.content;
                    font-size: 14px;
                }
            }
        }

        Rectangle {
            width: 100%;
            height: 5px;
            background: grey;
        }

        HorizontalLayout {
            alignment: end;
            Text {
                text: "Username";
                font-size: 14px;
                vertical-alignment: center;
            }
            Rectangle {
                width: 5px;
            }
            LineEdit {
                width: 100px;
                text: AppData.username;
            }
            Rectangle {
                width: 5px;
            }
            Button {
                text: "Settings";
            }
        }

        HorizontalLayout {
            alignment: end;
            Text {
                text: "Password";
                font-size: 14px;
                vertical-alignment: center;
            }
            Rectangle {
                width: 5px;
            }
            LineEdit {
                width: 100px;
            }
            Rectangle {
                width: 5px;
            }
            Button {
                text: "Play";
            }
        }
    }
}
